site_name: Extra Medium
site_url: https://bgarrison2.github.io/extra-medium
site-base-url: /extra-medium/

nav:
  - Home: index.md
  - Guides: 
    - Introduction: Guides/Intro.md
  - Recipes: 
    - Chili: recipes/chili.md
  - Blog:
    - blog/index.md
 
theme:
  name: material
  
  logo: assets/logo.png
  
  # Optional: Choose a color scheme (e.g., slate for dark mode)
  palette:
    scheme: primary
    
  # Optional: Show the file's last update date
  features:
    - content.action.edit
    - content.tabs.link
    - navigation.expand
    - navigation.instant
    - navigation.sections
    - navigation.tabs
    - navigation.indexes
    
  plugins:
    - blog

    
