site_name: Extra Medium
site_url: https://bgarrison2.github.io/extra-medium
site-base-url: /extra-medium/

nav:
  - Home: index.md
   
  - Guides: 
    - Getting started: Guides/Intro.md
    
  - Recipes:
    - Getting started:
    - Chicken Satay Chili: recipes/chicken-satay-chili.md
    
 
theme:
  name: material
  
  logo: assets/logo.png
  
  # Optional: Choose a color scheme (e.g., slate for dark mode)
  palette:
    scheme: primary
    
  # Optional: Show the file's last update date
  features:
    - content.action.edit
    - content.tabs.link
    - navigation.expand
    - navigation.instant
    - navigation.sections
    - navigation.tabs
    - navigation.indexes
    



    
